export const GET_ORDERS_FETCHING = 'GET_ORDERS_FETCHING'
export const GET_ORDERS_FULFILLED = 'GET_ORDERS_FULFILLED'
export const GET_ORDERS_REJECTED = 'GET_ORDERS_REJECTED'

export const ADD_ORDERS_FETCHING = 'ADD_ORDERS_FETCHING'
export const ADD_ORDERS_FULFILLED = 'ADD_ORDERS_FULFILLED'
export const ADD_ORDERS_REJECTED = 'ADD_ORDERS_REJECTED'

export const DELETE_ORDERS_FETCHING = 'DELETE_ORDERS_FETCHING'
export const DELETE_ORDERS_FULFILLED = 'DELETE_ORDERS_FULFILLED'
export const DELETE_ORDERS_REJECTED = 'DELETE_ORDERS_REJECTED'

export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
